import logging,re;from db import execute_query,get_connection,DB_MODE;logger=logging.getLogger(__name__)
def _safe(sql):
    if DB_MODE=="mysql":return sql
    sql=re.sub(r"COMMENT\s*=\s*'[^']*'","",sql);sql=re.sub(r"COMMENT\s+'[^']*'","",sql);sql=re.sub(r"UNIQUE\s+KEY\s+\w+\s*","UNIQUE ",sql);sql=re.sub(r",\s*KEY\s+\w+\s+\([^)]+\)","",sql)
    for o,n in {"INTEGER AUTO_INCREMENT PRIMARY KEY":"INTEGER PRIMARY KEY AUTOINCREMENT","DECIMAL(10,2)":"REAL","TINYINT(1)":"INTEGER","VARCHAR(255)":"TEXT","VARCHAR(100)":"TEXT","VARCHAR(50)":"TEXT","VARCHAR(30)":"TEXT","ENGINE=InnoDB":"","DEFAULT CHARSET=utf8mb4":"","ON UPDATE CURRENT_TIMESTAMP":""}.items():sql=sql.replace(o,n)
    return sql
TABLES={
    "temu_shipping_labels":"""CREATE TABLE IF NOT EXISTS temu_shipping_labels (label_id INTEGER AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,shop_id INT NOT NULL,sku VARCHAR(100) NOT NULL,order_id VARCHAR(100),label_data TEXT,status VARCHAR(20) DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES temu_users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发货标签';""",
    "temu_shipping_manifests":"""CREATE TABLE IF NOT EXISTS temu_shipping_manifests (manifest_id INTEGER AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,shop_id INT NOT NULL,order_ids TEXT,manifest_data TEXT,status VARCHAR(20) DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES temu_users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='发货单';""",
    "temu_activities":"""CREATE TABLE IF NOT EXISTS temu_activities (act_id INTEGER AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,shop_id INT NOT NULL,activity_id VARCHAR(100) NOT NULL,name VARCHAR(255),category_match VARCHAR(50),start_time TIMESTAMP,end_time TIMESTAMP,status VARCHAR(20) DEFAULT 'pending',applied_skus TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES temu_users(user_id) ON DELETE CASCADE,UNIQUE KEY uk_act (user_id,shop_id,activity_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平台活动';""",
    "temu_sensitive_words":"""CREATE TABLE IF NOT EXISTS temu_sensitive_words (word_id INTEGER AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,word VARCHAR(100) NOT NULL,level VARCHAR(20) DEFAULT 'high',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES temu_users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='敏感词库';""",
    "temu_inspection_records":"""CREATE TABLE IF NOT EXISTS temu_inspection_records (rec_id INTEGER AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,shop_id INT NOT NULL,sku VARCHAR(100) NOT NULL,field VARCHAR(50),content TEXT,risk_level VARCHAR(20),suggestion TEXT,status VARCHAR(20) DEFAULT 'pending',inspected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES temu_users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='巡检记录';""",
    "temu_reviews":"""CREATE TABLE IF NOT EXISTS temu_reviews (review_id INTEGER AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,shop_id INT NOT NULL,sku VARCHAR(100) NOT NULL,rating INT NOT NULL,content TEXT,keywords TEXT,category VARCHAR(50),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES temu_users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='评价数据';""",
    "temu_suppliers":"""CREATE TABLE IF NOT EXISTS temu_suppliers (supplier_id INTEGER AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,name VARCHAR(200) NOT NULL,contact VARCHAR(100),phone VARCHAR(50),main_category VARCHAR(50),rating DECIMAL(3,1) DEFAULT 5.0,status VARCHAR(20) DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES temu_users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商';""",
    "temu_supplier_products":"""CREATE TABLE IF NOT EXISTS temu_supplier_products (sp_id INTEGER AUTO_INCREMENT PRIMARY KEY,supplier_id INT NOT NULL,sku VARCHAR(100) NOT NULL,product_name VARCHAR(255),price DECIMAL(10,2),last_price DECIMAL(10,2),price_changed_at TIMESTAMP,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (supplier_id) REFERENCES temu_suppliers(supplier_id) ON DELETE CASCADE,UNIQUE KEY uk_sp (supplier_id,sku)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商商品';""",
    "temu_product_research":"""CREATE TABLE IF NOT EXISTS temu_product_research (pr_id INTEGER AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,source VARCHAR(50),title VARCHAR(255),price DECIMAL(10,2),sales_count INT,category VARCHAR(50),estimated_profit DECIMAL(10,2),estimated_margin DECIMAL(5,2),risk_level VARCHAR(20),status VARCHAR(20) DEFAULT 'pending',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY (user_id) REFERENCES temu_users(user_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='选品数据';""",
}
def initialize_tables():
    for tn,sql in TABLES.items():
        try:c=get_connection();cur=c.cursor();cur.execute(_safe(sql));cur.close();c.commit();c.close()
        except Exception as e:logger.error(f"创建表 {tn} 失败: {e}")
